### ISSUE TITLE
`yalc publish` throws an error

### ISSUE THREAD

**Issue by chrisbodhi** [whitecolor/yalc#1]
I realize that this is still in development, but I'm excited about the possibility of this tool greatly improving my team's workflow. Ran into this error when giving it a spin, though.

```
~/dependency ᐅ yalc publish
/bin/sh: yarn.lock: command not found
(node:67368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: yarn.lock
/bin/sh: yarn.lock: command not found
```

Looks like the error could be on this line? https://github.com/whitecolor/yalc/blob/master/src/index.ts#L93
And if that's it, https://nodejs.org/api/fs.html#fs_fs_existssync_path might be helpful.

yalc version 1.0.0-pre.5
yarn version 0.23.2
node version 6.9.4
os x version 10.11.6

**Comment by whitecolor** [comment]
Hi, glad that it may help, thanks for the report it was, should be fixed in the latest released!
