### ISSUE TITLE
install and postinstall scripts are not executed after yalc add, link, update

### ISSUE THREAD

**Issue by jmca** [whitecolor/yalc#100]
According to [NPM's docs](https://docs.npmjs.com/misc/scripts#description):
```
install, postinstall: Run AFTER the package is installed.
```

I'm thinking these scripts should be executed after the following commands:
`yalc add`
`yalc link`
`yalc update`

My specific use case is that I sometimes use git repos as packages. When those packages are installed, normally the `install` and `postinstall` scripts are executed in order to fire off a build step on the target machine.

At the moment, `install` and `postinstall` doesn't fire when using yalc.

**Comment by jmca** [comment]
Possibly `yalc push` too.

**Comment by idudinov** [comment]
wondering why this issue has been closed? 
just experienced this behaviour:

after doing `yalc push` client project doesn't notice that the package has been updated and `yarn` doesn't call `postinstall` for the package.

any workaround for this?

**Comment by wclr** [comment]
@idudinov read in https://github.com/wclr/yalc#update about pre/postyalc scripts

**Comment by idudinov** [comment]
> @idudinov read in https://github.com/wclr/yalc#update about pre/postyalc scripts

thanks, I've just tried it but no luck – on provider side, scripts `preyalc`, `postyalc` and `postupdate` just didn't work during the push w/ or w/o `--no-force` flag. Just noting that I don't want to add any additional scripts to the consumer side because I may not control them in future.

But I've found out what just works for me at the end of the day:

```
yalc push --replace --update
```

And anyway I want to say a BIG Thank You for this project because it really helps 🙌

**Comment by wclr** [comment]
> – on provider side, scripts preyalc, postyalc

This is client side scripts.  there is no `postupdate` script. there is `postyalcpublish` to run on the host side.

**Comment by idudinov** [comment]
thanks for the hint, but `postyalcpublish` still doesn't do what I need. It runs on the provider side, while I need my library to be built on the consumer side, while be triggered from the provider side and not adding additional scripts on the consumer's.

tbh, I got confused by terms `host` and `client`, `provider` and `consumer` look more straightforward imo.

**Comment by wclr** [comment]
There is a standard `postinstall` script for a package build step on install.

**Comment by idudinov** [comment]
> There is a standard `postinstall` script for a package build step on install.

I've tried that first, and I do have it at the moment to make my build action run during casual install. 

I know that `yalc` calculates provider package hash on each publish and includes it to the version, but on the consumer side `yarn` doesn't catch that, so `postinstall` isn't called after `yalc push`, even if I run `yarn` manually. What actually helps and does the trick is calling `yarn upgrade my-package` on the consumer side but initiated on the provider side.
