### ISSUE TITLE
When using with create-react-app I have to restart app for changes to appear

### ISSUE THREAD

**Issue by dutzi** [whitecolor/yalc#117]
1. I set up a create-react-app
2. Ran `yalc publish` from my module
3. Ran `yalc add my-module` from my app

Now whenever I run `yarn run build && yalc publish` followed by `yalc update` from my app I need to restart the app in order to see those changes.

**Comment by markusait** [comment]
I am experiencing the same issue. I am assuming this is because the dist folder from the module is used by your app. A fix for this would really help, ideally, if it also works with hot-reloading.

**Comment by haywirez** [comment]
I'm not sure how this would be possible to fix right now with CRA. My guess is that you'd need a custom HMR server that watches the `.yalc` folder and issues a rebuild.

**Comment by whitecolor** [comment]
Yalc just replaces old code with new one in your project. If your reloader watches source files that are delivered with yalc, that it should react to changes. Yalc just delivers new content.

**Comment by austinbutler** [comment]
You may be able to get something going with `craco` and a custom webpack plugin:

`craco.config.js`
```es6
const resolvePath = require("path");

class WatchExternalFilesPlugin {
  apply(compiler) {
    compiler.hooks.afterCompile.tapAsync(
      "WatchExternalFilesPlugin",
      (compilation, callback) => {
        ["./yalc.lock"].forEach((path) =>
          compilation.fileDependencies.add(resolvePath(path))
        );
        callback();
      }
    );
  }
}

module.exports = {
  webpack: {
    plugins: [new WatchExternalFilesPlugin()],
  },
};
```

**Comment by nvanrees** [comment]
FYI. I got my create-react-app to hot reload when making changes to my npm package (storybook) locally.
All I had to do was instead of using `yalc add <packageName>`, just use `yalc link <packageName>`. Now everytime I do `yalc push` in my storybook ui package, my create-react-app hot reloads after it is done pushing. Hope this helps!

**Comment by whitecolor** [comment]
This probably should be closed as the question.

**Comment by johot** [comment]
@nvanrees thank you! Your solution worked perfectly in my case :)
