### ISSUE TITLE
Use semver build metadata vs. pre-release

### ISSUE THREAD

**Issue by donavon** [whitecolor/yalc#120]
I have a package that has a semver [pre-release](https://semver.org/#spec-item-9) version of `0.1.0-beta.2` in my `pckage.json` file. After `yalc publish`-ing the package, the version appears as `0.1.0-beta.2-e23e875e`, which is an invalid server. 

Shouldn't yalc be appending a semver [build metadata](https://semver.org/#spec-item-10) segment instead?
(i.e.  `0.1.0-beta.2+e23e875e`)

**Comment by whitecolor** [comment]
You are right I believe, will change this.
