### ISSUE TITLE
yalc publish should run all of the lifecycle scripts it finds

### ISSUE THREAD

**Issue by Keysox** [whitecolor/yalc#129]
`yalc publish` is not running multiple lifecycle scripts and instead just executes the first one it finds. To match the behavior of npm and lerna, it would be great if it executed all of them. I'd be happy to make the change!

__Additional information:__

This used to be the behavior prior to https://github.com/whitecolor/yalc/commit/2708e145d93988112bea5b9583818f00ee294fa2#diff-d9a60851031c31a6d1f30fd69b639407R78.

https://github.com/whitecolor/yalc#user-content-publish states the following:
`
If your package has one of these lifecycle scripts: preyalc, prepare, prepack, prepublishOnly, prepublish, it will run before. If your package has one of these: postyalc or postpublish, it will run after. Use --force to publish without running scripts.
`

**Comment by whitecolor** [comment]
In what order scripts should be executed?

**Comment by Keysox** [comment]
https://docs.npmjs.com/misc/scripts and https://github.com/lerna/lerna/tree/master/commands/publish#lifecycle-scripts list information about each and when they should run. Here's the order:
```
prepublish,
prepare,
prepublishOnly,
prepack,
postpack,
publish,
postpublish
```

**Comment by whitecolor** [comment]
So you may add this change.
