### ISSUE TITLE
monorepo: when I clone the repo seems that the link path points to original source

### ISSUE THREAD

**Issue by cocodrino** [whitecolor/yalc#134]
hello, hope you're great,

I've a project like this

```
//inside folder folder1
app
|_package.json
|_node_modules
---proj1   <---main project
  |__package.json
  |__some lib <---- package used by proj1

```

**proj1** needs to use the project *some_lib*, I followed this article 

https://www.viget.com/articles/how-to-use-local-unpublished-node-packages-as-project-dependencies/

basically I did a `yalc publish` inside the some_lib and `yalc add some_lib inside my proj1`

this works fine, but now I clone the repo in another machine, suppose that this is named folder2, when I run `yalc publish push` the command says

```
Pushing some_lib@1.0.0 in /...full path/folder1/app/proj1
```

this must push in the folder2, not inside the folder1.....how can I force to update the package in some specific directory?

thank you so much

**Comment by whitecolor** [comment]
Copying the package you first should do `yalc update` in folders with `yalc.lock` file, it will pull the packages from store. Then push will work for them.

**Comment by cocodrino** [comment]
thank you @whitecolor that is exactly what I was looking for...
