### ISSUE TITLE
Add option to preserve .yalc folder after yalc remove

### ISSUE THREAD

**Issue by tyschroed** [whitecolor/yalc#136]
We have a project that uses Minikube + Docker + Skaffold for a development environment in a monorepo setup. Our dockerfiles are setup to pull in the `.yalc` folder so we can pick up local development changes, and skaffold is setup to watch the filessystem to trigger rebuilds. 

This all works fine until the last package is `yalc remove`'d in the project, at which point yalc deletes the `.yalc` folder. This causes Skaffold to error out, as it can no longer find the file referenced by the dockerfile. Would it be possible to add an option on `remove` similiar to `retreat` which would leave the empty `.yalc` folder in place so file watchers and docker files don't break?

**Comment by whitecolor** [comment]
Probably need to add check if it is empty after removing all the packages? So you can place there some file that will prevent deletion on remove operation's clean up.

**Comment by tyschroed** [comment]
Exactly. Currently we keep a .yalc folder, with a .gitkeep file within in checked into the repo. Perhaps there could be a --preserve-folder option that leaves the folder in place (with the .gitkeep file)? Alternatively before it deletes the folder maybe it could see if there is a .gitkeep file within in, it which case it leaves the folder?

**Comment by whitecolor** [comment]
I've actually implemented it and published, you may try, it won't delete the folder if something else is there after it cleans up all the packages

**Comment by tyschroed** [comment]
Just pulled it down. Seems to do the trick, thank you! One call out - we use scoped packages, and it looks like it left the top level `@scope` folder (with empty contents):

![image](https://user-images.githubusercontent.com/794198/93384464-b8694900-f819-11ea-932b-d3f459f91cb2.png)

**Comment by whitecolor** [comment]
@tyschroed ok will check it
