### ISSUE TITLE
`yalc push` run pre/post-scripts anyway

### ISSUE THREAD

**Issue by igoogolx** [whitecolor/yalc#137]
`--force` is useless

**Comment by igoogolx** [comment]
#138

**Comment by whitecolor** [comment]
there is `--no-scripts` flag

**Comment by igoogolx** [comment]
Ok! I found it in change-log. 
So `--force` flag is deprecated? 
It seems README needs to be updated.

**Comment by whitecolor** [comment]
Yes, updated it.
