### ISSUE TITLE
Unable to debug with breakpoints

### ISSUE THREAD

**Issue by balibebas** [whitecolor/yalc#140]
This was originally asked in #58 but the author closed the issue.

I'm trying to debug a Node app using Yalc. I'm starting node with the `--preserve-symlinks` option. When I attempt to set a breakpoint in my app and run the debugger I'm unable to get a bound breakpoint. This only occurs for packages linked to my app using Yalc.

<img width="815" alt="Screen Shot 2020-10-25 at 1 12 09 AM" src="https://user-images.githubusercontent.com/65664227/97087794-37467280-165f-11eb-953b-45fd57dee524.png">

In the above image I'm attempting to set my breakpoint in the `.yalc` directory. But it doesn't make a difference where it's set as the debugger isn't able to bind it. This feels more like a VSCode issue than a Yalc issue but I want to ask here first to understand what the real issue is so I can create a reduced test case.

Has anyone else run across this problem?

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by balibebas** [comment]
I got this figured out. The problem wasn't Yalc it was that a hot update to some node modules wasn't restarting the Node process. Added Nodemon and got it sorted out.

<img width="835" alt="Screen Shot 2020-10-25 at 3 48 00 AM" src="https://user-images.githubusercontent.com/65664227/97092247-138e2700-1675-11eb-814a-fbbbb21a1fb4.png">

**Comment by whitecolor** [comment]
Yalc is to simple to cause the problems 😄
