### ISSUE TITLE
Vulnerability in yargs dependency (GHSA-p9pc-299p-vxgp) 

### ISSUE THREAD

**Issue by erdbeereis** [whitecolor/yalc#142]
Hi 🌻
first of all thank you for great work! 

I am using yalc for an enterprise project. The builtin GitHub vulnerability check for dependencies gives me the following warning: 

> yargs-parser Known security vulnerability in 5.0.0-security.0 

It links to [this specific commit](https://github.com/yargs/yargs-parser/commit/63810ca1ae1a24b08293a4d971e70e058c7a41e2).

This version of `yargs-parser` is a dependency of `yargs` in version 7.1.1 which is a dependency of your project, noted as `^7.1.0`.

Are you aware of this issue? Do you plan to upgrade your `yargs` version to a more current one? Can you recommend a solution for this?

Thank you so much!

**Comment by whitecolor** [comment]
Updated and published.
