### ISSUE TITLE
Removing multiple packages together in the same org fails

### ISSUE THREAD

**Issue by AndrewLeedham** [whitecolor/yalc#146]
Hi @whitecolor great package, has been very useful for local development. I seem to have found a bug:

Node version: 14.15.0
Yalc version: 1.0.0-pre.48
Yarn version: 1.22.4
OS version: macOS Big Sur (11.1)

I am adding packages with `yalc add @org/package1 @org/package2` and I have
```
  "workspaces": [
    ".yalc/*",
    ".yalc/@*/*"
  ]
```
in my `package.json`, however using `yalc remove --all` or `yalc remove @org/package1 @org/package2` causes the error `Error: ENOENT: no such file or directory, scandir '/path/to/.yalc/@org'`, removing them individually with `yalc remove @org/package1` and `yalc remove @org/package2` works fine. So it seems there is some-sort of race condition when removing multiple packages in the same org at once.

**Comment by whitecolor** [comment]
Thanks, this should be fixed.

**Comment by AndrewLeedham** [comment]
Works like a charm thanks 👍
