### ISSUE TITLE
Auto publish on file changes

### ISSUE THREAD

**Issue by tforssander** [whitecolor/yalc#15]
Hi,

First och all thank you for this solution. I've been trying to get npm/yarn link working but have come across to many issues when working with symlinked packages which have driven me nuts. 

Now to my request, would it be possible to watch for any file changes in the added/linked package and publish it automatically so I don't have to manually run `yalc publish --push`? I tried reading the docs, so might have missed this. 

Thanks again! :)

**Comment by whitecolor** [comment]
Hi, there was a discussion on this matter https://github.com/whitecolor/yalc/issues/4

First, my point is that I actually not needed so much, I usually make some consistent changes to the package and then push it. If I have a code that is really in active development and need to be applied on each change I usually develop it as part of the project uses it, and when it is quite consistent I extract that code into the separate package.

But any way you may use for example `nodemon` for this: `nodemon -x 'yalc push'`?

**Comment by tforssander** [comment]
Ah, great!

Actually, I just noticed this and I agree with you on this. Also, since I have a playground in the package directory where I develop each component separately, I can push those changes when I want to try them in the actual project.

Will anyway try the nodemon solution, thanks again!
