### ISSUE TITLE
Added package as link is changed to file after push

### ISSUE THREAD

**Issue by dan-lee** [whitecolor/yalc#17]
Hey,

I've added a package (which is a sub-package in a folder) with following command: `yalc add --link project-x`.

Now my package json reads correctly:
```
dependencies: {
  "project-x": "link:./yalc/project-x"
}
```

But after `yalc push project-x` from my parent folder of `project-x`, my package.json looks like:
```
dependencies: {
  "project-x": "file:./yalc/project-x"
}
```

Did I miss something here?

**Comment by whitecolor** [comment]
Thanks for the notice, should be fixed in published version!

**Comment by dan-lee** [comment]
That was amazingly quick and I can confirm that it works correctly now. Thanks a bunch!
