### ISSUE TITLE
Publish seems to ignore folder in files section of package.json

### ISSUE THREAD

**Issue by rlodge** [whitecolor/yalc#2]
So I've got a files section like:
```json
  "files": [
    "dist/"
  ],
```
But when I run `yalc publish` the resulting directory never includes the "dist" directory.

**Comment by rlodge** [comment]
Maybe I've solved it myself as soon as I put this in . . . if I don't have the slash at the end it works fine.  *Should* it support directories with the slash like above?

**Comment by whitecolor** [comment]
It probably should I'll check it

**Comment by whitecolor** [comment]
Should be fixed.

**Comment by rlodge** [comment]
Confirmed that it fixes my case, thanks.
