### ISSUE TITLE
yalc too eager to ignore files

### ISSUE THREAD

**Issue by madgnome** [whitecolor/yalc#20]
It took me a while to figure out why one of my file named `historyFetcher.js` was not copied by yalk.

It turns out yalc exclude standard non-code files but do it with a broad brush:

```
var npmFilesIncludedByDefault = [
    'CHANGELOG*',
    'README*',
    'CHANGES*',
    'HISTORY*',
    'LICENSE*',
    'LICENCE*',
    'NOTICE*'
];
```
Any file starting with one of these keywords won't be included by yarn.

**Comment by whitecolor** [comment]
To ignore default included should be, I believe:

```
  'CHANGELOG',
  'README',
  'CHANGES',
  'HISTORY',
  'LICENSE',
  'LICENCE',
  'NOTICE',
  'CHANGELOG.*',
  'README.*',
  'CHANGES.*',
  'HISTORY.*',
  'LICENSE.*',
  'LICENCE.*',
  'NOTICE.*'
```

 though it would aslo ignore by default `history.js` for example.
