### ISSUE TITLE
Bin permissions

### ISSUE THREAD

**Issue by igbopie** [whitecolor/yalc#21]
Hi!

I have a dependency with an executable file (like [this one](http://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm)). I get a permissions error when I run it. I manually run chmod +x and everything goes fine. Maybe you can include that in the process.

Thanks!

**Comment by whitecolor** [comment]
I'm not sure what you mean, how do you add the package in to the project, using `yalc link`?

**Comment by igbopie** [comment]
So, on the dependency I run `yalc publish`. The on the host: `yalc update`, but after that, I have to run `chmod +x ./node_modules/.bin/[MYBINFILE]`, to make it work.

**Comment by whitecolor** [comment]
Ah I see, that because `yalc update` replaces the content in  `node_modules/package`, hm maybe there could be added for example `postupdate` script that would be run on `yalc update` in the projects folder, what do you think?

**Comment by igbopie** [comment]
I think `/node_modules/.bin/XXX` is a symbolic link to `/node_modules/YOUR_PACKAGE/SOME_FILE_YOU_SPECIFY_ON_PACKAGE_JSON`.

Yes, I think `postupdate` sounds fine! 👍

**Comment by igbopie** [comment]
I guess `yalc` will need to check package.json for this (for example):

```
"bin": {
  "github-pages-commit": "bin/commit.js",
  "github-pages-push": "bin/push.js",
  "github-pages-deploy": "bin/deploy.js"
}
``` 

then perform `postupdate` task to `chmod +x` the bin files specified.

**Comment by whitecolor** [comment]
Ok, I get you will check ASAP.

**Comment by diachedelic** [comment]
I am having this issue also - I don't want to have to manually chmod my bin folder every time I `yalc push`!

**Comment by whitecolor** [comment]
There was handing of `postupdate` added, it will run in the host package directory while yalc updates package that has `postupdate` in scripts.

**Comment by aleclarson** [comment]
Once #61 is merged, the `link` and `add` commands will support the `bin` field in `package.json` of yalc'd packages, which means the `node_modules/.bin` directory will be updated as expected. 😄

**Comment by eugeneoshepkov** [comment]
Any updates on this?
