### ISSUE TITLE
yalc ignores subdirectories such as 'lib/history'

### ISSUE THREAD

**Issue by christopherthielen** [whitecolor/yalc#23]
Yalc is ignoring subdirectories matching "standard non-code files" such as `lib/history/**`

The workaround listed in the README (adding an explicit include to `.npmignore` such as `!history` or `!**/history` or `!lib/history`) does not work for subdirectories because of how the `ignore()` function works

@whitecolor  can you provide some context on why should the standard non-code globs be ignored in any case?  It seems more consistent to me to include all files that `npm pack` would have included. 

I've provided a PR which limits the standard non-code globs to the root of the package, but in my opinion, I'd rather see the blacklist removed.

**Comment by whitecolor** [comment]
Think should be fixed.
