### ISSUE TITLE
Link behavior is not preserved for Update/Push

### ISSUE THREAD

**Issue by emjelde** [whitecolor/yalc#26]
When using the link command the documentation states that it will not touch `package.json` and is similar to `npm/yarn link`. This behavior is not preserved for subsequent uses of `yalc update` and `yalc push` and the package.json is updated to include `link:` dependencies.

**Comment by whitecolor** [comment]
Thanks =) Fixed.

**Comment by emjelde** [comment]
I'm not seeing the changes on GitHub, but noticed that you had published to npm. In testing this my `package.json` now remains unchanged.

Thanks for the quick response and fix!

**Comment by whitecolor** [comment]
Forgot to push)
