### ISSUE TITLE
Feature request: `yalc unlink`

### ISSUE THREAD

**Issue by guillaumearm** [whitecolor/yalc#27]
Hi,

It would be nice to have a `yalc unlink` command.

I am forced to remove the symbolic link manually before re-install when I want to unlink a package, it's not very practical.

Anyway, thanks 🙏 for this amazing module ❤️ , it saved my life 🤣

**Comment by whitecolor** [comment]
Hi, what does this command has to do in paticular? For example `yarn unlink` just removes linked directory, if i'm not mistaken it still do not reinstall original package, have to do `yarn` after .

**Comment by guillaumearm** [comment]
I have issues when I remove manually a yalc link and I do `yarn`, nothing appened.
I have to remove `node_modules` and make a full re-install.

Because yalc is supposed to bring a better workflow for make links,

- `yalc link` would save the original `node_modules/concerned-module` directory (somewhere in the `.yalc` ?)
- `yalc unlink` would replace the link by the saved original folder

**Comment by whitecolor** [comment]
> yalc unlink would replace the link by the saved original folder

`yarn/npm unlink` doesn't seem to restore the previous folder. Is not not cleare how it should be "saved" for the future and is it worth do so. Whats the problem of running `yarn` after? Do you link/unlink multiple times a day?

**Comment by guillaumearm** [comment]
> Do you link/unlink multiple times a day?

Yes, actually on my project, using `yarn install` take some times because I have to recompile some native dependencies, it's not related to `yalc`.

I thought having a `yalc unlink` command allow me to optimize this process, but it's not the good solution.

Like you said: 

> yarn/npm unlink doesn't seem to restore the previous folder. Is not not cleare how it should be "saved" for the future and is it worth do so.

Anyway, thanks for your time, I guess you can close this issue.

**Comment by aleclarson** [comment]
We could make `yarn unlink` an alias for `yarn remove`.
