### ISSUE TITLE
`npm pack` ignores directories differently than `yalc publish`

### ISSUE THREAD

**Issue by greyepoxy** [whitecolor/yalc#29]
**Repo:**
Create a test project (I called mine `test-delete`) with the following contents
+ examples
  + `example.js`
+ lib
  + examples
    + `example.js`
  + src
    + `file.js`
  + `alwaysIgnored.txt`
+ src
  + `file.js`
+ `.npmignore` ->
  ```
  examples/
  src/*
  alwaysIgnored.txt
  ```
+ `alwaysIgnored.txt`
+ `package.json` -> `{ "name": "@test/test-delete",  "version": "0.0.1" }`

Actual: get by running `yalc publish`, navigate to yalc working path (for me on win10 `%localappdata%/Yalc/packages/@test/test-delete/0.0.1`)
+ lib
  + src
    + `file.js`
+ `package.json`
+ (note: also includes `.npmignore` and `yalc.sig` which is expected)

Expected: get by running `npm pack`, package has the following contents
+ lib
  + examples
    + `example.js`
  + src
    + `file.js`
+ `package.json`

I was expecting `yalc publish` to output the same file contents as `npm pack` but in the case of a directory defined in the `.npmignore` it does not (in this repo the `examples/` directory). Looks like unlike as advertised in the [`.npmignore` docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) directories work differently than in [`.gitignore` files](https://git-scm.com/docs/gitignore).

**Comment by greyepoxy** [comment]
Going to try and put together a pull request to fix this if I can figure out some of the subtle here

**Comment by whitecolor** [comment]
Ignoring in yalc was implemented in a bit tricky way, and maybe not the best approach was taken to emulate npm/yarn behavior. If you will come up with a more consistent solution in principle, it would be nice)

**Comment by whitecolor** [comment]
It now uses `npm-packlist`, so it should be ok now! Also handling of `.yalcignore` file was added.

**Comment by greyepoxy** [comment]
Yep tested and it worked as expected, thanks so much!
