### ISSUE TITLE
Watch scripts break on `yalc push`

### ISSUE THREAD

**Issue by greyepoxy** [whitecolor/yalc#34]
## Problem
When running a watch script in a package consuming another local package that has been marked as a local dependency using yalc. When `yalc push` is called in the consumed package an error occurs and the watch script breaks in the consuming package.

Example of the error:
```
D:\repos\test-delete> yalc push
Pushing @test/test-delete@0.0.1 in D:\repos\test-delete-watcher
(node:31748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EPERM: operation not permitted, lstat 'D:\repos\test-delete-watcher\.yalc\@test\test-delete\lib\index.js'
(node:31748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Repo
Create two projects with the following files/contents
**test-delete**
- lib
  - `index.js`
- `package.json`
  ```
  {
      "name": "@test/test-delete",
      "version": "0.0.1",
      "main": "lib/index.js"
  }  
  ```

**test-delete-watcher**
- src
  - `index.js`
    ```
    require('@test/test-delete');
    ```
- `package.json`
  ```
  {
    "name": "@test/test-delete-watcher",
    "version": "0.0.0",
    "scripts": {
      "bundle": "webpack",
      "watch": "webpack --watch"
    },
    "dependencies": {
      "@test/test-delete": "file:../test-delete"
    },
    "devDependencies": {
      "webpack": "4.17.1",
      "webpack-command": "0.4.1"
    }
  }
  ```

in *test-delete-watcher* run `yarn install` (to get the webpack dependencies so that `yarn run bundle` and `yarn run watch` will work)

in *test-delete* run `yalc publish`

in *test-delete-watcher* run `yalc add @test/test-delete`

in *test-delete-watcher* run `yarn run watch` to start bundling and watching for changes

in *test-delete* run `yalc push`

See the failure above
Also in `test-delete-watcher/node_modules/@test/test-delete` the `src/index.js` file is now missing

To get the system to work again have to run `yalc push` in *test-delete* and restart the watch in *test-delete-watcher*

### System info
64-bit windows 10

**Comment by greyepoxy** [comment]
Looks like the issue in the code is that the script just deletes the directory and then copies in the new content https://github.com/whitecolor/yalc/blob/master/src/add.ts#L117. For it to be more friendly to watch scripts would need it to add any new files first, then update existing, and then delete removed files.

I will see if I can put together some possible solutions

**Comment by whitecolor** [comment]
I believe I was thinking about such possible issue and wanted to make something like --push-safe flag which will just overwrite content in destination dir without deleting it at first. But seems I haven't implemented it. I'm not sure if it will fix your issue.

**Comment by greyepoxy** [comment]
okay will see if I can give that a shot

**Comment by whitecolor** [comment]
What particular current action of yalc is causing the error?
Removing the directory or copying new content?

**Comment by whitecolor** [comment]
The better form of the solution I see the following:

create a separate module with function with i.e `copyRepace` method, that will take source path (in store) and dest path, then will take the list of files in the source and replace in the dest if changed, removes files that exist in the dest, not in the source dir.

I believe you have already implemented this in PR, but it is very big and has many other unrelated changes. So PR for solving really should include this module with `copyReplace` function and a few lines changed in `add` module. I would rather deal with really small incremental changes.

**Comment by greyepoxy** [comment]
Yes what you describe is exactly what I implemented in `replaceContentsOfDirectory` https://github.com/whitecolor/yalc/pull/48/files#diff-636831b11c3a6df21b0ac29b1b90f88dR219

I agree should probably be its own package but disagree that we need to do that now (can always extract and replace it later, as long as its better, safe, and no worse then I usually encourage moving forward)

You are right that there are unrelated, safe changes that I made in the process of reading/understanding the code. Each step of that was done incrementally and documented as a commit https://github.com/whitecolor/yalc/pull/48/commits.

If you feel strongly about it I can revert all of the unrelated changes if you would like. My approach is based on the assumption that the next contributor will only benefit from my insights if I document them (through introducing names with extract functions, and renaming existing names).

**Comment by greyepoxy** [comment]
I made a second pull request that only includes the required changes https://github.com/whitecolor/yalc/pull/49 (no random extract functions or renames), let me know what you think

**Comment by ffgregormueller** [comment]
This would be really helpful!

**Comment by whitecolor** [comment]
Should not be the case anymore.

**Comment by quantuminformation** [comment]
is --safe still a flag?
