### ISSUE TITLE
Meta-Feature Request: Roadmap and current features checklist

### ISSUE THREAD

**Issue by ajhool** [whitecolor/yalc#35]
Really excited to see this project because development has been a serious pain point with Workspaces. Would like to jump in right away and start using it and am curious how feature complete this project is. For instance, are people using this with Workspaces? In their own projects?

I know it's in pre-stage, but working with links in Workspaces and Lerna has been challenging so a buggy-but-working yalc would still be really nice.

Edit: Also, FWIW, it might be useful to describe this approach as a "Flux" unidirectional architecture for local dependency management. This might resonate with the React/front-end crowd. Rather than children tracking the state of other children, all changes are committed to a parent (the local registry) and the parent then pushes the data down to the children. As far as I can tell, this is a flux architecture for dependency management and solves the same general problem that React solved

**Comment by whitecolor** [comment]
Hi, thanks for the attention. Actually, Yalc is projected to be a simple tool. It is supposed to do what it currently does: easier incorporation of EXTERNAL packages that under are current (active) development (usually by single responsible dev) into different projects. Something like that. And maybe tasks that usually solved using `yarn/npm link`.

I'm not sure that yalc is capable of doing something like lerna or workspaces are intended to do. 

Though I like your idea about "unidirectional state management".

**Comment by whitecolor** [comment]
Will close this for now.
