### ISSUE TITLE
`yalc remove` leaves a symlink in `node_modules`

### ISSUE THREAD

**Issue by erikphansen** [whitecolor/yalc#37]
After using `yalc link` I used `yalc remove` to tell Yalc to clean up after itself. However it leaves a link behind in the consuming app's `node_modules` folder. That link has to be removed manually before you can run `yarn install --check-files` to switch back to using the NPM version of the module you were testing.

At the very least I'd expect that `yalc remove` would completely clean up after itself so that you don't have the manually remove the link. Bonus points would be awarded if running `yalc remove` also restored the NPM version of the module.

**Comment by whitecolor** [comment]
> However it leaves a link behind in the consuming app's node_modules folder

It doesn't seem to be so. `yalc remove xxx` removes `your_package/node_modules/xxx`.
