### ISSUE TITLE
pulling dependencies

### ISSUE THREAD

**Issue by akosyakov** [whitecolor/yalc#4]
I would like to start a script that watches local dependencies and incrementally update corresponding content of .yalc folder.

Make sense? How do you do it now? Call `yalc publish --push` on each change?

**Comment by whitecolor** [comment]
Currenlty while (`yalc push`) makes a lot of fs operations, first clears up cache folder copies there, clears up folders in installations and copies there fresh content, I'm not sure how well it would work with watching mode. 

Well, I thought about such scenario too, and wanted to implement kind of `--safe` flag that would not remove old content and just copy fresh one on top, to less interfere with watches that my lock files/folders from removal.

So need to try. But really I refused to use this practice of instant updates, I make some more or less consistent changes to the package code then push it and check if works as expected.

**Comment by whitecolor** [comment]
If I need to check something quickly in the current project I may just to try to fix it in the `node-modules`, and then introduce the change in the package if it is needed. This is kind of workflow I use.

**Comment by whitecolor** [comment]
In my view if you really need instant updates of some code in your project it should probably be *the real part* of your project, not dependency package code. There is a certain balance needed.

**Comment by akosyakov** [comment]
Even without instant updates, it would be nice to run `build` on the dependent package and be sure that all local dependencies are up to date. Make it continuous could be the second step.

**Comment by whitecolor** [comment]
> it would be nice to run build on the dependent package and be sure that all local dependencies are up to date. 

You mean run build of dependency package from a dependant project? I think this an arguable idea. 
But this command could be called `yalc pull` :smile:

**Comment by akosyakov** [comment]
It is a normal practice in more mature build systems as gradle for java. If one package has A task which relies on a result of B task in another package then performing A will make sure that result of B is up to date.

**Comment by whitecolor** [comment]
Then I'm not sure what particular workflow you mean.

**Comment by akosyakov** [comment]
> You mean run build of dependency package from a dependant project? I think this an arguable idea.

I meant that is not arguable in other build systems, they just do it.

**Comment by whitecolor** [comment]
I think this may break the consistency, what would be the workflow?

- make some changes to dep package
- But you don't publish it 
- Then dependant project you do `pull` and yalc publishes dep package and adds the latest to the project.

Why not just make push/publish after changes? This just more consistent.

**Comment by aleclarson** [comment]
I haven't tried yet, but wouldn't using `yarn link` (instead of yalc) in this scenario work just fine?
