### ISSUE TITLE
Can a repo be unpublished?

### ISSUE THREAD

**Issue by kemalcany** [whitecolor/yalc#46]
Hi there!

This is a great repo and it makes our workflow so much easier! So thanks for that...

I was wondering if there is an option to 'unpublish' packages once they are published. The reason I am asking is because of a situation like this:

- Repo A is a component to be yalced and it will be used by few projects. So this repo is `yalc publish`ed.

- Project A and project B both are using the repo A. So they have `yalc add`ed repo A.

- Later on Project B was deleted from the file system.

And now, when you try to `yalc push` the repo A, it gives a warning that it can't find the package.json of the Project B (since it is deleted). It works without problems with the Project A symlink.

Since project B is deleted I cannot do a `yalc remove` from that directory. Is there a way to remove this link from the repo A's side?

I hope I managed to explain the problem. Happy to provide more information if required.

Thank you for the great work! Cheers!

**Comment by whitecolor** [comment]
Well, that is not about unpublishing/removing from local repo of the package A right? Its about installations stored. I i'm thinking about adding command something like `yalc clean-installations` that will take the installations file and check all the directories, it if not existing project/directory found it will wipe it out of stored installations and will not try to install there anymore. 

I'm not sure that this operation should be implicit, that is why want to do it with special command.

**Comment by kemalcany** [comment]
Yes correct! It's all about the stored installations on the repo that is published by yalc. So I think your idea of a `yalc clean-installations` would be spot on to fix these warnings!

**Comment by whitecolor** [comment]
Check `yalc installations clean` in the latest published.

**Comment by kemalcany** [comment]
Works like a charm! Awesome! Thanks a lot! 🥇
