### ISSUE TITLE
Support prepare script when publishing

### ISSUE THREAD

**Issue by czycha** [whitecolor/yalc#52]
The `prepublish` script behavior has been [deprecated](https://docs.npmjs.com/misc/scripts#deprecation-note) in NPM since v1.1.71 and replaced with `prepare`. For better interoperability between yalc and npm/yarn, I think yalc's publish command should run the prepare script as well as or instead of prepublish.

**Comment by whitecolor** [comment]
Ok, will add support next published version.

**Comment by czycha** [comment]
Saw that this was published in `1.0.0-pre.26`. Thanks!
