### ISSUE TITLE
Unpublish command?

### ISSUE THREAD

**Issue by FredyC** [whitecolor/yalc#54]
It's merely a concern of having obsolete stuff in a local repository. I just like to keep stuff clean. I know I can simply go to the user profile directory and delete the package from there, but it's kinda annoying manual step :) Then, of course, there is an `installations.json` which should be manually edited, but it doesn't matter in the end.

Ideally, I can imagine that `yalc unpublish` would check for existing installation and list them if any of those still exists. If there are none, it's safe to remove the package. The `--force` argument could remove the package from all installations instead of having to manually remove it everywhere.

Thinking about it now, there is actually no command to find out where the package is installed, hmm. That alone is kinda useful before doing a push imo.

Thank you very much for Yalc either way, it's super helpful especially on Windows where symlinks can be rather weird. I am using it heavily for packages under development. It's amazingly simple way as other team members don't need to any concern with it when I commit `.yalc` directory. 🎉

**Comment by whitecolor** [comment]
Thanks) Ok will add probably, there is also `yalc installations clean [package]`.

**Comment by FredyC** [comment]
> Thinking about it now, there is actually no command to find out where the package is installed, hmm. That alone is kinda useful before doing a push imo.

Just noticed there is actually `yalc installations show` also, but it's not documented and it doesn't even show up with `yalc --help`. The `clean` is not there as well.

**Comment by FredyC** [comment]
Hm, so you have changed your mind about it?

**Comment by whitecolor** [comment]
About what? Unpublish command? What the real use case for it?

**Comment by FredyC** [comment]
Well, I thought that first comment convinced you enough since you agreed. If it doesn't anymore then forget about it.

**Comment by ojvribeiro** [comment]
> What the real use case for it?

Maybe remove the package from global store? Or can we safely delete the folder from `.yalc/packages` without worrying about deep linkings?
