### ISSUE TITLE
Why is yalc accessing github?

### ISSUE THREAD

**Issue by rickbsgu** [whitecolor/yalc#56]
I'm under the impression that yalc allows local access of local repos, yes?

When I do a 'yalc publish' in a local copy of a repo, it does a 'git push && git push --tags', neither of which I want to happen.

**Comment by whitecolor** [comment]
Hi, probably this in your `pre/post` scripts?

**Comment by rickbsgu** [comment]
It's a pretty vanilla install.  I haven't done anything other than install it and executing 'publish'.

'postyalc' yields 'command not found'.

**Comment by whitecolor** [comment]
Will close it for now.
