### ISSUE TITLE
Should you run `rm -rf node_modules; yarn install` afterward?

### ISSUE THREAD

**Issue by yang** [whitecolor/yalc#77]
Is my understanding correct that running just the `yalc` commands as documented won't address various issues with `yarn link`, such as not installing transitive dependencies and not installing new/renamed bin scripts?  (It's reasons like these that were our main motivation for looking into `yalc` in the first place.)

I spent some time experimenting, and it seems that running `rm -rf node_modules/; yarn install` afterward *does* patch up these issues.  Just wanted to check that my mental model of how yalc/yarn are supposed to be used is correct, since this smells...non-ideal.  (Running `yarn install` doesn't seem to do anything since it just does a quick "Resolving..." scan and reports "success Already up-to-date.") 

If this is the case, then it may be worth at least mentioning in the documentation (where there's the NB about "but it doesn't execute yarn/npm install/update commands after this").  Thanks!

**Comment by yang** [comment]
Actually, this approach of blowing away node_modules also does not work with `yarn link`, only with `yarn add` (which edits your package.json).

`yarn install --force` does not work either, fails when it encounters the unexpected symlink with "EEXIST: file already exists: mkdir."

Advice appreciated!

**Comment by conartist6** [comment]
Second this. The docs don't say anything like: `yalc link` is great so long as you don't have any transitive dependencies.

**Comment by whitecolor** [comment]
Do you mean by `transitive dependencies` dependencies of linked package? `yalk link` works the same way as `npm link` in terms of deps.

**Comment by conartist6** [comment]
My experience using it today is that none of the modules dependencies are installed at all, which means that any module with dependencies will be broken after linking.

**Comment by whitecolor** [comment]
Its not broken, it just works this way. If you want deps to be installed you have to add them in package.json anyway, this is how npm or yarn work with deps.

**Comment by whitecolor** [comment]
Probably should close this.

**Comment by conartist6** [comment]
Wait, what? I have to copy all the dependencies of the package I'm trying to link into my package??? Maybe it was clearer when we were calling them transitive dependencies, which they are.

Could you please reopen this issue while we're still trying to figure out if we're talking about the same thing?

**Comment by conartist6** [comment]
Also that is definitely not how `npm link` works. The npm strategy works because all the linked package's dependencies are installed in the global `node_modules` when you run `npm link`.

**Comment by whitecolor** [comment]
@conartist6 
Yes you are right, probably running 'npm install' in `.yalc/package` would help. I actually didn't think about it because I don't use `yalc link` at all.
