### ISSUE TITLE
yalc does not retain file permissions

### ISSUE THREAD

**Issue by van-nguyen** [whitecolor/yalc#80]
The use case is I want to test the `install` script in package without publishing it remotely. However when I run `yalc` then `yalc add` it packs all fine except the permissions are not retained.

before

```
-rwxr-xr-x    1 van  staff    1126 Apr 17 23:42 sync.js
```

after

```
-rw-r--r--   1 van  staff    1126 Apr 17 23:44 sync.js
```

As you can see the execute permissions has been stripped, therefore I cannot execute my script as it's meant to.

When I run `yarn install --force`

It gives me this error

```
/bin/sh: ./sync.js: Permission denied
```

**Comment by metasean** [comment]
See issue #21, pr #61, & pr #63

Sadly, based on the number of [open PRs](https://github.com/whitecolor/yalc/pulls), it looks like @whitecolor stopped maintaining this project last fall.

**Comment by whitecolor** [comment]
@metasean Not at all. Will close the issue as soon release the fix.
