### ISSUE TITLE
Troubleshoot module not found

### ISSUE THREAD

**Issue by bbbryan14** [whitecolor/yalc#83]
I used yalc publish and yalc add. The module is showing up in package.json, but project still cannot resolve the module. What are some trouble shooting steps I can take?

**Comment by whitecolor** [comment]
run yarn/npm install?

**Comment by bbbryan14** [comment]
I figured it out. It's a Typescript project being used as dependency in a JS project, and I didn't check in the build folder.

**Comment by fluxquantum** [comment]
Hi I am also having this issue. I swapped out a particular dependency and add an updated version of it in my package.json, but now my components can't find the module by name anymore. I tried changing the path to the dependency to point to the .yalc folder but it's not working in my react project. 

I have ran npm i, and also tried removing and then re-adding the dependencies, but still getting a module not found.

I was using the steps here as a guide. Is there someone that can guide my trouble shooting. Thanks.

**Comment by oskrgg** [comment]
I have same issue @bbbryan14 . How did you solve it? How do you know if JS or TS project? 😬  Regards

**Comment by fbjorn** [comment]
@bbbryan14 ping, I'd also appreciate to know how to handle it

**Comment by oskrgg** [comment]
Build the project.
Getting the .dist directory worked for me
