### ISSUE TITLE
yalc publish fails with pre.29 with file perm is 444

### ISSUE THREAD

**Issue by atomicpages** [whitecolor/yalc#84]
This might be somewhat niche, but my company uses Perforce which automatically (and annoyingly) sets _all_ files with the permission to `444`. `pre.29` after 543d26de61b85a03e098a2adc0e7de448306e83c fails with:

```
(node:56902) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Users/USER/.yalc/packages/yalcc/1.0.0/index.js'
(node:56902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can there be a flag on the publish command that allows us to do an unsafe copy? I'm happy to make a PR. LMK :+1:

## Repro

Here's a small shell script to test it out:

```bash
mkdir sample && cd sample
npm init -y
echo "module.exports = {};" > index.js
chmod 444 index.js
npx yalc publish
```

**Comment by whitecolor** [comment]
Have fixed it used `preserveTimestamps` option of fs-extra's copy method, but seems it is not needed.

**Comment by atomicpages** [comment]
Works like a charm! Thanks!
