### ISSUE TITLE
Anyone have a nice workflow for developing a React distributable lib + updating a CRA example using Yalc?

### ISSUE THREAD

**Issue by corysimmons** [whitecolor/yalc#89]
I'm assuming one of the primary use cases of Yalc is to work on a package locally and watch that package and see the changes directly reflected in CRA (especially lately with React Hooks forcing dupe React dependencies to throw).

Does anyone have a nice workflow for this? I noticed some chatter about it in a few "watch" related issues, but feel like this is a common enough pattern to deserve some sort of example in the README/docs.

Thanks for the wonderful lib. It's exactly what `npm/yarn link` should be.

**Comment by whitecolor** [comment]
I don't use watching with yalc at all. There should no problems, with latest changes replacement of modified versions should be very graceful and should cause now issues.

probably something like `nodemon -x yalc push` should work.

**Comment by corysimmons** [comment]
Nice that should work, thank you.
