### ISSUE TITLE
Ignores .yalc folder in files section of package.json

### ISSUE THREAD

**Issue by GazzaHazza** [whitecolor/yalc#9]
I've got a files section like:

```
"files": [
    "dist/",
   ".yalc/"
  ],
```
But no folder exists when I publish.

**Comment by whitecolor** [comment]
I'll check it, thanks.

**Comment by GazzaHazza** [comment]
Wow thanks for quick reply, and thanks for checking! I might be doing it wrong but I am having issue when i have a yalc'd package as a dependency of another yalc'd package if that makes sense?

**Comment by whitecolor** [comment]
Fixed it, not sure why I placed `.yalc` files in ignore rules by default.

**Comment by GazzaHazza** [comment]
Thanks for the quick fix and great package 👍
