### ISSUE TITLE
Yalc cannot add package with character @

### ISSUE THREAD

**Issue by dalaverd** [whitecolor/yalc#91]
Yalc doesn't detect properly character @ when adding a new package to a project.

For example "@company\my-package" it just get resolved as "company\my-package"

**Comment by dalaverd** [comment]
I have managed to make it work but only by using "/" character in my path instead of backslashes

**Comment by whitecolor** [comment]
I believe using `\` in package name is not valid.

**Comment by soanvig** [comment]
Works for me.
