### ISSUE TITLE
Run prepack?

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [whitecolor/yalc#92]
Hi there, thanks for the awesome package. It's really helping me to avoid npm link frustrations. I have a suggestion that might be good:

npm's ["prepack" script](https://docs.npmjs.com/misc/scripts) runs "before `npm pack`, `npm publish` and when installing git dependencies".

As a library author I have `prepack` scripts in all my libraries in order to make sure a clean build always executes before `npm pack` or `npm publish`.

It seems that this is the purpose of the script: to transform a repo from its "source" form to its "package" form. (This is why it also happens for git dependencies, since those are raw sources that haven't been packaged yet). https://github.com/avajs/ava/issues/1541 is an example of someone choosing to add a prepack script so that their library could be installed from a git url.

Since the yalc store is meant to hold locally-published packages, I think `yalc publish` should also run `prepack`, since the command is in line with `npm publish`. If the package has no `prepack` script, then nothing will happen, but if it does, then the package author definitely intends for it to be run at publish time.

### Current state
`yalc publish` runs these pre* scripts:
- prepublishOnly
- prepublish
- prepare
- preyalc

However, they don't hit the spot like prepack.
- prepublishOnly does not run for `npm pack`
- prepublish (the precursor to prepublishOnly and prepare) is [advised against](https://docs.npmjs.com/misc/scripts#deprecation-note).
- prepare is like prepack but also runs on `npm install`.
- preyalc scripts are not used by npm

What do you think? Should yalc run "prepack" on `yalc publish`?

**Comment by whitecolor** [comment]
> What do you think? Should yalc run "prepack" on yalc publish?

Yes, I belive it should.)

**Comment by matthiasdailey-ccri** [comment]
Here's a PR!: https://github.com/whitecolor/yalc/pull/93
